import StatCard from "./StatCard";
import QuickAction from "./QuickAction";
import RecentOrders from "./RecentOrders";
import SalesChart from "./SalesChart";
import AIInsights from "./AIInsights";
import KPIBar from "./KPIBar";

interface DashboardPageProps {
  merchant?: {
      id: string;
          store_name: string;
              tenant_id: string;
                  subdomain: string;
                      industry?: string;
                        };
                          productCount?: number;
                            orderCount?: number;
                            }

                            export default function DashboardPage({ 
                              merchant,
                                productCount = 0,
                                  orderCount = 0
                                  }: DashboardPageProps) {
                                    return (
                                        <div className="space-y-8">

                                              {/* Header */}
                                                    <div>
                                                            <h1 className="text-3xl font-bold text-white">
                                                                      Welcome back, {merchant?.store_name || "Merchant"}!
                                                                              </h1>

                                                                                      <p className="mt-2 text-zinc-400">
                                                                                                Your {merchant?.industry || "Commerce"} dashboard
                                                                                                        </p>
                                                                                                              </div>

                                                                                                                    {/* KPI Bar */}
                                                                                                                          <KPIBar />

                                                                                                                                {/* Stats */}
                                                                                                                                      <div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-4">

                                                                                                                                              <StatCard
                                                                                                                                                        title="Total Products"
                                                                                                                                                                  value={productCount.toString()}
                                                                                                                                                                            subtitle="In your catalog"
                                                                                                                                                                                      icon="🛍️"
                                                                                                                                                                                              />

                                                                                                                                                                                                      <StatCard
                                                                                                                                                                                                                title="Total Orders"
                                                                                                                                                                                                                          value={orderCount.toString()}
                                                                                                                                                                                                                                    subtitle="All time"
                                                                                                                                                                                                                                              icon="📦"
                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                              <StatCard
                                                                                                                                                                                                                                                                        title="Store Status"
                                                                                                                                                                                                                                                                                  value="Active"
                                                                                                                                                                                                                                                                                            subtitle={`${merchant?.subdomain || "N/A"}.baazarify.pk`}
                                                                                                                                                                                                                                                                                                      icon="🟢"
                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                      <StatCard
                                                                                                                                                                                                                                                                                                                                title="Industry"
                                                                                                                                                                                                                                                                                                                                          value={merchant?.industry || "General Store"}
                                                                                                                                                                                                                                                                                                                                                    subtitle="Your business category"
                                                                                                                                                                                                                                                                                                                                                              icon="🏷️"
                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                  {/* Quick Actions */}
                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="mb-4 text-xl font-semibold text-white">
                                                                                                                                                                                                                                                                                                                                                                                                          Quick Actions
                                                                                                                                                                                                                                                                                                                                                                                                                  </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-4">

                                                                                                                                                                                                                                                                                                                                                                                                                                    <QuickAction
                                                                                                                                                                                                                                                                                                                                                                                                                                                title="Add Product"
                                                                                                                                                                                                                                                                                                                                                                                                                                                            description="Create a new product"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        href="/products/new"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    icon="➕"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <QuickAction
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title="View Orders"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                description="Manage your orders"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/orders"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        icon="📦"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <QuickAction
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title="AI Studio"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description="Open AI tools"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                href="/ai"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            icon="🤖"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <QuickAction
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title="Store Settings"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        description="Customize your store"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    href="/settings"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                icon="⚙️"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Sales Chart */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <SalesChart />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Recent Orders + AI Insights */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="grid gap-6 xl:grid-cols-3">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="xl:col-span-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <RecentOrders />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <AIInsights />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              