const orders = [
      {
          id: "#1001",
              customer: "Ali Khan",
                  amount: "Rs. 4,500",
                      status: "Paid",
                        },
                          {
                              id: "#1002",
                                  customer: "Sara Ahmed",
                                      amount: "Rs. 2,850",
                                          status: "Pending",
                                            },
                                              {
                                                  id: "#1003",
                                                      customer: "Usman Ali",
                                                          amount: "Rs. 8,100",
                                                              status: "Shipped",
                                                                },
                                                                ];

                                                                export default function RecentOrders() {
                                                                  return (
                                                                      <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6">
                                                                            <div className="mb-6 flex items-center justify-between">
                                                                                    <h2 className="text-xl font-bold text-white">
                                                                                              Recent Orders
                                                                                                      </h2>

                                                                                                              <button className="text-sm font-medium text-emerald-400 hover:text-emerald-300">
                                                                                                                        View All
                                                                                                                                </button>
                                                                                                                                      </div>

                                                                                                                                            <div className="space-y-4">
                                                                                                                                                    {orders.map((order) => (
                                                                                                                                                              <div
                                                                                                                                                                          key={order.id}
                                                                                                                                                                                      className="flex items-center justify-between rounded-xl border border-zinc-800 p-4"
                                                                                                                                                                                                >
                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                          <p className="font-semibold text-white">
                                                                                                                                                                                                                                          {order.id}
                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                      <p className="text-sm text-zinc-400">
                                                                                                                                                                                                                                                                                      {order.customer}
                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                            <div className="text-right">
                                                                                                                                                                                                                                                                                                                                          <p className="font-semibold text-white">
                                                                                                                                                                                                                                                                                                                                                          {order.amount}
                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                      <span
                                                                                                                                                                                                                                                                                                                                                                                                      className={`text-xs font-medium ${
                                                                                                                                                                                                                                                                                                                                                                                                                        order.status === "Paid"
                                                                                                                                                                                                                                                                                                                                                                                                                                            ? "text-emerald-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                : order.status === "Pending"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? "text-yellow-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : "text-blue-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {order.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              