"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase/client";

interface Order {
  id: string;
    order_number: string;
      customer_name: string;
        total: number;
          status: string;
            payment_status: string;
              created_at: string;
              }

              const statusColors = {
                pending: "bg-yellow-500/15 text-yellow-400",
                  processing: "bg-blue-500/15 text-blue-400",
                    shipped: "bg-purple-500/15 text-purple-400",
                      delivered: "bg-emerald-500/15 text-emerald-400",
                        cancelled: "bg-red-500/15 text-red-400",
                        };

                        const paymentColors = {
                          unpaid: "bg-red-500/15 text-red-400",
                            paid: "bg-emerald-500/15 text-emerald-400",
                              refunded: "bg-orange-500/15 text-orange-400",
                              };

                              export default function OrderTable({ orders }: { orders: Order[] }) {
                                const router = useRouter();

                                  const updateStatus = async (id: string, status: string) => {
                                      try {
                                            const { error } = await supabase
                                                    .from("orders")
                                                            .update({ status })
                                                                    .eq("id", id);

                                                                          if (error) throw error;
                                                                                router.refresh();
                                                                                    } catch (err) {
                                                                                          alert("Failed to update order status.");
                                                                                              }
                                                                                                };

                                                                                                  if (!orders || orders.length === 0) {
                                                                                                      return (
                                                                                                            <div className="empty-state">
                                                                                                                    <p className="empty-state-title">No orders yet</p>
                                                                                                                            <p className="empty-state-description">Orders will appear here once customers place them.</p>
                                                                                                                                  </div>
                                                                                                                                      );
                                                                                                                                        }

                                                                                                                                          return (
                                                                                                                                              <div className="table-container">
                                                                                                                                                    <table className="min-w-full">
                                                                                                                                                            <thead className="table-header">
                                                                                                                                                                      <tr>
                                                                                                                                                                                  <th className="table-header-cell">Order</th>
                                                                                                                                                                                              <th className="table-header-cell">Customer</th>
                                                                                                                                                                                                          <th className="table-header-cell">Total</th>
                                                                                                                                                                                                                      <th className="table-header-cell">Status</th>
                                                                                                                                                                                                                                  <th className="table-header-cell">Payment</th>
                                                                                                                                                                                                                                              <th className="table-header-cell">Date</th>
                                                                                                                                                                                                                                                          <th className="table-header-cell text-right">Actions</th>
                                                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                                                            </thead>
                                                                                                                                                                                                                                                                                    <tbody>
                                                                                                                                                                                                                                                                                              {orders.map((order) => (
                                                                                                                                                                                                                                                                                                          <tr key={order.id} className="table-row">
                                                                                                                                                                                                                                                                                                                        <td className="table-cell font-medium text-white">
                                                                                                                                                                                                                                                                                                                                        #{order.order_number}
                                                                                                                                                                                                                                                                                                                                                      </td>
                                                                                                                                                                                                                                                                                                                                                                    <td className="table-cell text-zinc-300">
                                                                                                                                                                                                                                                                                                                                                                                    {order.customer_name}
                                                                                                                                                                                                                                                                                                                                                                                                  </td>
                                                                                                                                                                                                                                                                                                                                                                                                                <td className="table-cell font-medium text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                Rs. {order.total.toFixed(2)}
                                                                                                                                                                                                                                                                                                                                                                                                                                              </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td className="table-cell">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={order.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => updateStatus(order.id, e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className={`rounded-full px-3 py-1 text-xs font-semibold ${statusColors[order.status as keyof typeof statusColors] || "bg-zinc-500/15 text-zinc-400"} border-none outline-none cursor-pointer`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="pending">Pending</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="processing">Processing</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="shipped">Shipped</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="delivered">Delivered</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="cancelled">Cancelled</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td className="table-cell">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className={`rounded-full px-3 py-1 text-xs font-semibold ${paymentColors[order.payment_status as keyof typeof paymentColors] || "bg-zinc-500/15 text-zinc-400"}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {order.payment_status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td className="table-cell text-zinc-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {new Date(order.created_at).toLocaleDateString()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td className="table-cell text-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href={`/orders/${order.id}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="text-sm text-emerald-400 hover:underline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          View
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  