"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase/client";

export default function CreateStorePage() {
  const router = useRouter();
    const [storeName, setStoreName] = useState("");
      const [industry, setIndustry] = useState("");
        const [loading, setLoading] = useState(false);
          const [error, setError] = useState<string | null>(null);

            const industries = [
                "Fashion",
                    "Beauty",
                        "Electronics",
                            "Jewelry",
                                "Perfumes",
                                    "Home & Living",
                                        "Digital Products",
                                            "General Store",
                                              ];

                                                const handleCreateStore = async (e: React.FormEvent) => {
                                                    e.preventDefault();
                                                        setLoading(true);
                                                            setError(null);

                                                                try {
                                                                      const { data: { user } } = await supabase.auth.getUser();

                                                                            if (!user) {
                                                                                    router.push("/login");
                                                                                            return;
                                                                                                  }

                                                                                                        const tenantId = `tn_${Math.random().toString(36).substring(2, 10)}`;
                                                                                                              const subdomain = storeName
                                                                                                                      .toLowerCase()
                                                                                                                              .replace(/[^a-z0-9]/g, "-");

                                                                                                                                    const { error: merchantError } = await supabase
                                                                                                                                            .from("merchants")
                                                                                                                                                    .insert({
                                                                                                                                                              user_id: user.id,
                                                                                                                                                                        store_name: storeName,
                                                                                                                                                                                  industry,
                                                                                                                                                                                            tenant_id: tenantId,
                                                                                                                                                                                                      subdomain,
                                                                                                                                                                                                              });

                                                                                                                                                                                                                    if (merchantError) throw merchantError;

                                                                                                                                                                                                                          router.push("/dashboard");
                                                                                                                                                                                                                              } catch (err: any) {
                                                                                                                                                                                                                                    setError(err.message || "Failed to create store.");
                                                                                                                                                                                                                                        } finally {
                                                                                                                                                                                                                                              setLoading(false);
                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                          <div className="flex min-h-screen items-center justify-center bg-black px-4">
                                                                                                                                                                                                                                                                <div className="w-full max-w-md rounded-2xl border border-zinc-800 bg-zinc-950 p-8">
                                                                                                                                                                                                                                                                        <div className="mb-8 text-center">
                                                                                                                                                                                                                                                                                  <h1 className="text-2xl font-bold text-white">Create Your Store</h1>
                                                                                                                                                                                                                                                                                            <p className="mt-2 text-sm text-zinc-400">
                                                                                                                                                                                                                                                                                                        Let's get your business online in minutes
                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                  <form onSubmit={handleCreateStore} className="space-y-6">
                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                        <label className="block text-sm font-medium text-zinc-300">
                                                                                                                                                                                                                                                                                                                                                                      Store Name
                                                                                                                                                                                                                                                                                                                                                                                  </label>
                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                            type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                          value={storeName}
                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setStoreName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-3 text-white outline-none focus:border-emerald-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="My Awesome Store"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label className="block text-sm font-medium text-zinc-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Industry
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={industry}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setIndustry(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-3 text-white outline-none focus:border-emerald-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="">Select your industry</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {industries.map((ind) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option key={ind} value={ind}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {ind}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="rounded-xl bg-red-500/10 p-3 text-sm text-red-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full rounded-xl bg-emerald-500 py-3 font-semibold text-black transition hover:bg-emerald-400 disabled:opacity-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading ? "Creating store..." : "Create Store"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }