"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";

import { sidebarNavigation } from "@/config/navigation";
import { useSidebar } from "@/hooks/useSidebar";

export default function Sidebar() {
  const pathname = usePathname();
    const { closeSidebar } = useSidebar();

      return (
          <aside className="flex h-full w-72 flex-col border-r border-zinc-800 bg-zinc-950">

                {/* Logo */}
                      <div className="flex h-16 items-center border-b border-zinc-800 px-6">
                              <div>
                                        <h1 className="text-lg font-bold text-white">
                                                    Baazarify
                                                              </h1>

                                                                        <p className="text-xs text-zinc-500">
                                                                                    Commerce OS
                                                                                              </p>
                                                                                                      </div>
                                                                                                            </div>

                                                                                                                  {/* Navigation */}
                                                                                                                        <nav className="flex-1 overflow-y-auto px-3 py-4">

                                                                                                                                <ul className="space-y-1">

                                                                                                                                          {sidebarNavigation.map((item) => {

                                                                                                                                                      const active = pathname === item.href;

                                                                                                                                                                  return (
                                                                                                                                                                                <li key={item.href}>

                                                                                                                                                                                                <Link
                                                                                                                                                                                                                  href={item.href}
                                                                                                                                                                                                                                    onClick={closeSidebar}
                                                                                                                                                                                                                                                      className={`
                                                                                                                                                                                                                                                                          flex
                                                                                                                                                                                                                                                                                              items-center
                                                                                                                                                                                                                                                                                                                  justify-between
                                                                                                                                                                                                                                                                                                                                      rounded-xl
                                                                                                                                                                                                                                                                                                                                                          px-4
                                                                                                                                                                                                                                                                                                                                                                              py-3
                                                                                                                                                                                                                                                                                                                                                                                                  transition-all
                                                                                                                                                                                                                                                                                                                                                                                                                      duration-200

                                                                                                                                                                                                                                                                                                                                                                                                                                          ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                active
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ? "bg-emerald-500 text-black font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : "text-zinc-300 hover:bg-zinc-900 hover:text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      `}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex items-center gap-3">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {item.icon}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {item.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {item.badge && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="rounded bg-blue-600 px-2 py-0.5 text-[10px] font-bold text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {item.badge}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </ul>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Footer */}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="border-t border-zinc-800 p-4">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="rounded-xl bg-zinc-900 p-4">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-sm font-medium text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Baazarify
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="mt-1 text-xs text-zinc-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Commerce OS v0.1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </aside>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  