"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase/client";

interface Product {
  id: string;
    name: string;
      category: string;
        sku: string;
          price: number;
            stock: number;
              status: string;
              }

              export default function ProductTable({ products }: { products: Product[] }) {
                const router = useRouter();

                  const handleDelete = async (id: string) => {
                      if (!confirm("Are you sure you want to delete this product?")) return;

                          try {
                                const { error } = await supabase
                                        .from("products")
                                                .delete()
                                                        .eq("id", id);

                                                              if (error) throw error;

                                                                    router.refresh();
                                                                        } catch (err) {
                                                                              alert("Failed to delete product.");
                                                                                  }
                                                                                    };

                                                                                      if (!products || products.length === 0) {
                                                                                          return (
                                                                                                <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-12 text-center">
                                                                                                        <p className="text-zinc-400">No products found.</p>
                                                                                                                <Link
                                                                                                                          href="/products/new"
                                                                                                                                    className="mt-4 inline-block rounded-xl bg-emerald-500 px-4 py-2 font-semibold text-black transition hover:bg-emerald-400"
                                                                                                                                            >
                                                                                                                                                      Add Your First Product
                                                                                                                                                              </Link>
                                                                                                                                                                    </div>
                                                                                                                                                                        );
                                                                                                                                                                          }

                                                                                                                                                                            return (
                                                                                                                                                                                <div className="overflow-x-auto rounded-2xl border border-zinc-800 bg-zinc-950">
                                                                                                                                                                                      <table className="min-w-full">
                                                                                                                                                                                              <thead className="border-b border-zinc-800 bg-zinc-950">
                                                                                                                                                                                                        <tr>
                                                                                                                                                                                                                    <th className="px-6 py-4 text-left text-sm font-semibold text-zinc-300">Product</th>
                                                                                                                                                                                                                                <th className="px-6 py-4 text-left text-sm font-semibold text-zinc-300">Category</th>
                                                                                                                                                                                                                                            <th className="px-6 py-4 text-left text-sm font-semibold text-zinc-300">SKU</th>
                                                                                                                                                                                                                                                        <th className="px-6 py-4 text-left text-sm font-semibold text-zinc-300">Price</th>
                                                                                                                                                                                                                                                                    <th className="px-6 py-4 text-left text-sm font-semibold text-zinc-300">Stock</th>
                                                                                                                                                                                                                                                                                <th className="px-6 py-4 text-left text-sm font-semibold text-zinc-300">Status</th>
                                                                                                                                                                                                                                                                                            <th className="px-6 py-4 text-right text-sm font-semibold text-zinc-300">Actions</th>
                                                                                                                                                                                                                                                                                                      </tr>
                                                                                                                                                                                                                                                                                                              </thead>
                                                                                                                                                                                                                                                                                                                      <tbody>
                                                                                                                                                                                                                                                                                                                                {products.map((product) => (
                                                                                                                                                                                                                                                                                                                                            <tr key={product.id} className="border-b border-zinc-800 hover:bg-zinc-800/40">
                                                                                                                                                                                                                                                                                                                                                          <td className="px-6 py-5 font-medium text-white">{product.name}</td>
                                                                                                                                                                                                                                                                                                                                                                        <td className="px-6 py-5 text-zinc-400">{product.category || "-"}</td>
                                                                                                                                                                                                                                                                                                                                                                                      <td className="px-6 py-5 text-zinc-400">{product.sku || "-"}</td>
                                                                                                                                                                                                                                                                                                                                                                                                    <td className="px-6 py-5 font-medium text-white">Rs. {product.price}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                  <td className="px-6 py-5 text-zinc-400">{product.stock}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                <td className="px-6 py-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className={`rounded-full px-3 py-1 text-xs font-semibold ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      product.status === "active"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ? "bg-emerald-500/15 text-emerald-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : product.status === "draft"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ? "bg-yellow-500/15 text-yellow-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : "bg-red-500/15 text-red-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {product.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td className="px-6 py-5 text-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex justify-end gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    href={`/products/${product.id}/edit`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="rounded-lg border border-zinc-700 px-3 py-2 text-sm text-white transition hover:border-emerald-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Edit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => handleDelete(product.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="rounded-lg border border-red-700 px-3 py-2 text-sm text-red-400 transition hover:bg-red-500/10"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Delete
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          