// lib/theme-engine/schemas.ts
import { SectionSchema } from '@/types/theme';

export const SECTION_SCHEMAS: Record<string, SectionSchema> = {
  'hero-banner': {
      type: 'hero-banner',
          name: 'Hero Banner',
              settings: [
                    {
                            id: 'heading',
                                    label: 'Heading',
                                            type: 'text',
                                                    default: 'Summer Collection 2026',
                                                          },
                                                                {
                                                                        id: 'subheading',
                                                                                label: 'Subheading',
                                                                                        type: 'textarea',
                                                                                                default: 'Discover our latest items.',
                                                                                                      },
                                                                                                            {
                                                                                                                    id: 'buttonText',
                                                                                                                            label: 'Button Label',
                                                                                                                                    type: 'text',
                                                                                                                                            default: 'Shop Now',
                                                                                                                                                  },
                                                                                                                                                        {
                                                                                                                                                                id: 'buttonLink',
                                                                                                                                                                        label: 'Button Link',
                                                                                                                                                                                type: 'text',
                                                                                                                                                                                        default: '#',
                                                                                                                                                                                              },
                                                                                                                                                                                                    {
                                                                                                                                                                                                            id: 'alignment',
                                                                                                                                                                                                                    label: 'Content Alignment',
                                                                                                                                                                                                                            type: 'select',
                                                                                                                                                                                                                                    default: 'center',
                                                                                                                                                                                                                                            options: [
                                                                                                                                                                                                                                                      { label: 'Left', value: 'left' },
                                                                                                                                                                                                                                                                { label: 'Center', value: 'center' },
                                                                                                                                                                                                                                                                          { label: 'Right', value: 'right' },
                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                      id: 'height',
                                                                                                                                                                                                                                                                                                              label: 'Banner Height',
                                                                                                                                                                                                                                                                                                                      type: 'select',
                                                                                                                                                                                                                                                                                                                              default: 'medium',
                                                                                                                                                                                                                                                                                                                                      options: [
                                                                                                                                                                                                                                                                                                                                                { label: 'Small', value: 'small' },
                                                                                                                                                                                                                                                                                                                                                          { label: 'Medium', value: 'medium' },
                                                                                                                                                                                                                                                                                                                                                                    { label: 'Large', value: 'large' },
                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                          'featured-products': {
                                                                                                                                                                                                                                                                                                                                                                                              type: 'featured-products',
                                                                                                                                                                                                                                                                                                                                                                                                  name: 'Featured Products Grid',
                                                                                                                                                                                                                                                                                                                                                                                                      settings: [
                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                    id: 'title',
                                                                                                                                                                                                                                                                                                                                                                                                                            label: 'Section Title',
                                                                                                                                                                                                                                                                                                                                                                                                                                    type: 'text',
                                                                                                                                                                                                                                                                                                                                                                                                                                            default: 'Trending Products',
                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                id: 'subtitle',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        label: 'Subtitle',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type: 'text',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        default: 'Our handpicked selection',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            id: 'productCount',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    label: 'Number of Products to Show',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type: 'range',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    default: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            min: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    max: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            step: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id: 'columns',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        label: 'Grid Columns (Desktop)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type: 'range',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        default: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                min: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        max: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                step: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    id: 'showVendor',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            label: 'Show Brand/Vendor Name',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type: 'switch',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            default: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id: 'showPrice',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        label: 'Show Product Price',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type: 'switch',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        default: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'rich-text': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type: 'rich-text',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              name: 'Rich Text',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  settings: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id: 'title',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        label: 'Heading',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type: 'text',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        default: 'Crafted for Quality',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            id: 'content',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    label: 'Body Text',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type: 'textarea',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    default: 'We believe in delivering top-notch products tailored for everyday comfort and style.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        id: 'alignment',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                label: 'Text Alignment',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type: 'select',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                default: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        options: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { label: 'Left', value: 'left' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { label: 'Center', value: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { label: 'Right', value: 'right' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          