// components/themes/sections/FeaturedProducts.tsx
import React from 'react';

interface Product {
  id: string;
    title: string;
      price: string;
        image: string;
          vendor?: string;
          }

          interface FeaturedProductsProps {
            id: string;
              settings: {
                  title?: string;
                      subtitle?: string;
                          productCount?: number;
                              columns?: number;
                                  showVendor?: boolean;
                                      showPrice?: boolean;
                                        };
                                        }

                                        // Mock Products Fallback Data
                                        const MOCK_PRODUCTS: Product[] = [
                                          { id: '1', title: 'Minimalist Leather Watch', price: 'PKR 4,999', vendor: 'Aura', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500' },
                                            { id: '2', title: 'Classic Cotton T-Shirt', price: 'PKR 1,850', vendor: 'BasicCo', image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=500' },
                                              { id: '3', title: 'Wireless Noise Canceling Earbuds', price: 'PKR 6,499', vendor: 'SoundX', image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500' },
                                                { id: '4', title: 'Ergonomic Desk Mat', price: 'PKR 2,200', vendor: 'WorkSpace', image: 'https://images.unsplash.com/photo-1616410011236-7a42121dd981?w=500' },
                                                ];

                                                export default function FeaturedProducts({ id, settings }: FeaturedProductsProps) {
                                                  const {
                                                      title = 'Trending Products',
                                                          subtitle = 'Our handpicked selection',
                                                              productCount = 4,
                                                                  columns = 4,
                                                                      showVendor = true,
                                                                          showPrice = true,
                                                                            } = settings;

                                                                              const displayProducts = MOCK_PRODUCTS.slice(0, productCount);

                                                                                const gridColsClass: Record<number, string> = {
                                                                                    2: 'grid-cols-1 sm:grid-cols-2',
                                                                                        3: 'grid-cols-1 sm:grid-cols-2 md:grid-cols-3',
                                                                                            4: 'grid-cols-1 sm:grid-cols-2 md:grid-cols-4',
                                                                                              };

                                                                                                return (
                                                                                                    <section id={id} className="w-full py-12 md:py-16 px-6 bg-slate-50">
                                                                                                          <div className="max-w-7xl mx-auto">
                                                                                                                  {(title || subtitle) && (
                                                                                                                            <div className="text-center mb-10 space-y-2">
                                                                                                                                        {title && <h2 className="text-2xl sm:text-3xl font-bold text-slate-900">{title}</h2>}
                                                                                                                                                    {subtitle && <p className="text-slate-600 text-sm sm:text-base">{subtitle}</p>}
                                                                                                                                                              </div>
                                                                                                                                                                      )}

                                                                                                                                                                              <div className={`grid gap-6 ${gridColsClass[columns] || gridColsClass[4]}`}>
                                                                                                                                                                                        {displayProducts.map((product) => (
                                                                                                                                                                                                    <div
                                                                                                                                                                                                                  key={product.id}
                                                                                                                                                                                                                                className="group bg-white rounded-xl border border-slate-200 overflow-hidden shadow-sm hover:shadow-md transition-shadow"
                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                          <div className="aspect-square w-full overflow-hidden bg-slate-100 relative">
                                                                                                                                                                                                                                                                          <img
                                                                                                                                                                                                                                                                                            src={product.image}
                                                                                                                                                                                                                                                                                                              alt={product.title}
                                                                                                                                                                                                                                                                                                                                className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                            <div className="p-4 space-y-1">
                                                                                                                                                                                                                                                                                                                                                                                            {showVendor && product.vendor && (
                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-xs font-semibold uppercase tracking-wider text-slate-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                  {product.vendor}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-sm font-semibold text-slate-800 line-clamp-1 group-hover:text-blue-600 transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {product.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {showPrice && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-sm font-bold text-slate-900 pt-1">{product.price}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                