'use client';

import React from 'react';

interface Product {
  id: string;
    name: string;
      price: string;
        image: string;
          category: string;
          }

          const MOCK_PRODUCTS: Product[] = [
            {
                id: '1',
                    name: 'Premium Leather Wallet',
                        price: 'Rs. 2,499',
                            image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=500&q=80',
                                category: 'Accessories',
                                  },
                                    {
                                        id: '2',
                                            name: 'Minimalist Wrist Watch',
                                                price: 'Rs. 5,999',
                                                    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&q=80',
                                                        category: 'Watches',
                                                          },
                                                            {
                                                                id: '3',
                                                                    name: 'Wireless Noise Earbuds',
                                                                        price: 'Rs. 4,200',
                                                                            image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&q=80',
                                                                                category: 'Electronics',
                                                                                  },
                                                                                    {
                                                                                        id: '4',
                                                                                            name: 'Classic Sunglasses',
                                                                                                price: 'Rs. 1,850',
                                                                                                    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500&q=80',
                                                                                                        category: 'Eyewear',
                                                                                                          },
                                                                                                          ];

                                                                                                          interface FeaturedProductsProps {
                                                                                                            settings?: {
                                                                                                                title?: string;
                                                                                                                    subtitle?: string;
                                                                                                                        columns?: string | number;
                                                                                                                            productsCount?: number;
                                                                                                                                bgColor?: string;
                                                                                                                                  };
                                                                                                                                  }

                                                                                                                                  export function FeaturedProducts({ settings }: FeaturedProductsProps) {
                                                                                                                                    const cols = String(settings?.columns || '3');
                                                                                                                                      const gridClass =
                                                                                                                                          cols === '2'
                                                                                                                                                ? 'grid-cols-1 sm:grid-cols-2'
                                                                                                                                                      : cols === '4'
                                                                                                                                                            ? 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-4'
                                                                                                                                                                  : 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3';

                                                                                                                                                                    const limit = Number(settings?.productsCount || 3);
                                                                                                                                                                      const displayedProducts = MOCK_PRODUCTS.slice(0, limit);

                                                                                                                                                                        return (
                                                                                                                                                                            <section
                                                                                                                                                                                  className="py-14 px-6 transition-all duration-300 border-b border-slate-100"
                                                                                                                                                                                        style={{ backgroundColor: settings?.bgColor || '#ffffff' }}
                                                                                                                                                                                            >
                                                                                                                                                                                                  <div className="max-w-6xl mx-auto">
                                                                                                                                                                                                          <div className="text-center mb-10">
                                                                                                                                                                                                                    <h2 className="text-3xl font-extrabold text-slate-900 tracking-tight">
                                                                                                                                                                                                                                {settings?.title || 'Featured Products'}
                                                                                                                                                                                                                                          </h2>
                                                                                                                                                                                                                                                    {settings?.subtitle && (
                                                                                                                                                                                                                                                                <p className="text-sm text-slate-500 mt-2">{settings.subtitle}</p>
                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                          <div className={`grid ${gridClass} gap-6`}>
                                                                                                                                                                                                                                                                                                    {displayedProducts.map((product) => (
                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                              key={product.id}
                                                                                                                                                                                                                                                                                                                                            className="group bg-white rounded-xl overflow-hidden border border-slate-200 shadow-sm hover:shadow-md transition-all duration-300"
                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                      <div className="aspect-square w-full overflow-hidden bg-slate-100 relative">
                                                                                                                                                                                                                                                                                                                                                                                      <img
                                                                                                                                                                                                                                                                                                                                                                                                        src={product.image}
                                                                                                                                                                                                                                                                                                                                                                                                                          alt={product.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="p-4 flex flex-col justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-[10px] font-semibold uppercase tracking-wider text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {product.category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="font-semibold text-slate-800 text-base mt-2 line-clamp-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {product.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-4 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-lg font-bold text-slate-900">{product.price}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button className="px-3 py-1.5 text-xs font-medium bg-slate-900 text-white rounded-lg hover:bg-slate-800 transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Add to Cart
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default FeaturedProducts;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          