'use client';

import React, { useEffect, useState } from 'react';
import { defaultThemeConfig, ExtendedThemeConfig } from '@/lib/theme-engine/default-theme';
import { StorefrontRenderer } from '@/components/theme/StorefrontRenderer';
import { StoreNavbar, StoreFooter } from '@/components/theme/sections/HeaderFooter';

export default function StorePreviewPage() {
  const [config, setConfig] = useState<ExtendedThemeConfig>(defaultThemeConfig);

    useEffect(() => {
        const handleMessage = (event: MessageEvent) => {
              const { type, payload } = event.data || {};

                    if (type === 'REORDER_SECTIONS') {
                            setConfig((prev) => ({ ...prev, layout_order: payload.layoutOrder }));
                                  }
                                        if (type === 'UPDATE_SECTION_SETTING') {
                                                const { sectionId, settingId, value } = payload;
                                                        setConfig((prev) => ({
                                                                  ...prev,
                                                                            sections: (prev.sections || []).map((sec) =>
                                                                                        sec.id === sectionId
                                                                                                      ? { ...sec, settings: { ...(sec.settings || {}), [settingId]: value } }
                                                                                                                    : sec
                                                                                                                              ),
                                                                                                                                      }));
                                                                                                                                            }
                                                                                                                                                  if (type === 'ADD_SECTION') {
                                                                                                                                                          const { section } = payload;
                                                                                                                                                                  setConfig((prev) => ({
                                                                                                                                                                            ...prev,
                                                                                                                                                                                      sections: [...(prev.sections || []), section],
                                                                                                                                                                                                layout_order: [...(prev.layout_order || []), section.id],
                                                                                                                                                                                                        }));
                                                                                                                                                                                                              }
                                                                                                                                                                                                                    if (type === 'REMOVE_SECTION') {
                                                                                                                                                                                                                            const { sectionId } = payload;
                                                                                                                                                                                                                                    setConfig((prev) => ({
                                                                                                                                                                                                                                              ...prev,
                                                                                                                                                                                                                                                        sections: (prev.sections || []).filter((s) => s.id !== sectionId),
                                                                                                                                                                                                                                                                  layout_order: (prev.layout_order || []).filter((id) => id !== sectionId),
                                                                                                                                                                                                                                                                          }));
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                      if (type === 'UPDATE_GLOBAL_SETTING') {
                                                                                                                                                                                                                                                                                              const { key, value } = payload;
                                                                                                                                                                                                                                                                                                      setConfig((prev) => ({
                                                                                                                                                                                                                                                                                                                ...prev,
                                                                                                                                                                                                                                                                                                                          global_settings: {
                                                                                                                                                                                                                                                                                                                                      ...prev.global_settings,
                                                                                                                                                                                                                                                                                                                                                  [key]: value,
                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                    }));
                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                  window.addEventListener('message', handleMessage);
                                                                                                                                                                                                                                                                                                                                                                                      return () => window.removeEventListener('message', handleMessage);
                                                                                                                                                                                                                                                                                                                                                                                        }, []);

                                                                                                                                                                                                                                                                                                                                                                                          const styles = config.global_settings || defaultThemeConfig.global_settings;

                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                                                                      className="min-h-screen flex flex-col justify-between transition-colors duration-200"
                                                                                                                                                                                                                                                                                                                                                                                                            style={
                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                              backgroundColor: styles.backgroundColor,
                                                                                                                                                                                                                                                                                                                                                                                                                                        color: styles.textColor,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontFamily: styles.fontFamily,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            '--primary-color': styles.primaryColor,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      '--accent-color': styles.accentColor,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } as React.CSSProperties
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <StoreNavbar brandName="BAAZARIFY STORE" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <main className="flex-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <StorefrontRenderer config={config} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <StoreFooter brandName="BAAZARIFY STORE" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              