"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { AuthService } from "@/services/auth/auth.service";

export default function LoginPage() {
  const router = useRouter();
    const [email, setEmail] = useState("");
      const [password, setPassword] = useState("");
        const [loading, setLoading] = useState(false);
          const [error, setError] = useState<string | null>(null);

            const handleLogin = async (e: React.FormEvent) => {
                e.preventDefault();
                    setLoading(true);
                        setError(null);

                            try {
                                  await AuthService.signIn(email, password);
                                        router.push("/dashboard");
                                            } catch (err: any) {
                                                  setError(err.message || "Login failed. Please try again.");
                                                      } finally {
                                                            setLoading(false);
                                                                }
                                                                  };

                                                                    return (
                                                                        <div className="flex min-h-screen items-center justify-center bg-black px-4">
                                                                              <div className="w-full max-w-md rounded-2xl border border-zinc-800 bg-zinc-950 p-8">
                                                                                      <div className="mb-8 text-center">
                                                                                                <h1 className="text-2xl font-bold text-white">Welcome Back</h1>
                                                                                                          <p className="mt-2 text-sm text-zinc-400">
                                                                                                                      Sign in to your Baazarify account
                                                                                                                                </p>
                                                                                                                                        </div>

                                                                                                                                                <form onSubmit={handleLogin} className="space-y-6">
                                                                                                                                                          <div>
                                                                                                                                                                      <label className="block text-sm font-medium text-zinc-300">
                                                                                                                                                                                    Email
                                                                                                                                                                                                </label>
                                                                                                                                                                                                            <input
                                                                                                                                                                                                                          type="email"
                                                                                                                                                                                                                                        value={email}
                                                                                                                                                                                                                                                      onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                  className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-3 text-white outline-none focus:border-emerald-500"
                                                                                                                                                                                                                                                                                                placeholder="you@example.com"
                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                            <label className="block text-sm font-medium text-zinc-300">
                                                                                                                                                                                                                                                                                                                                                          Password
                                                                                                                                                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                type="password"
                                                                                                                                                                                                                                                                                                                                                                                                              value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-3 text-white outline-none focus:border-emerald-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="••••••••"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="rounded-xl bg-red-500/10 p-3 text-sm text-red-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full rounded-xl bg-emerald-500 py-3 font-semibold text-black transition hover:bg-emerald-400 disabled:opacity-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {loading ? "Signing in..." : "Sign In"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="mt-6 text-center text-sm text-zinc-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Don't have an account?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link href="/signup" className="text-emerald-400 hover:underline">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Create one
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }