'use client';

import React, { useState, useEffect } from 'react';
import { ThemeConfig, CustomizerMessagePayload } from '@/types/theme';
import StorefrontRenderer from './StorefrontRenderer';

interface ThemePreviewWrapperProps {
  initialConfig: ThemeConfig;
  }

  export default function ThemePreviewWrapper({ initialConfig }: ThemePreviewWrapperProps) {
    const [config, setConfig] = useState<ThemeConfig>(initialConfig);

      useEffect(() => {
          // Admin Customizer se aane wale PostMessage events listen karne ke liye
              const handleMessage = (event: MessageEvent<CustomizerMessagePayload>) => {
                    const { type, payload } = event.data || {};

                          if (!type) return;

                                switch (type) {
                                        case 'UPDATE_GLOBAL_SETTINGS':
                                                  setConfig((prev) => ({
                                                              ...prev,
                                                                          settings: { ...prev.settings, ...payload },
                                                                                    }));
                                                                                              break;

                                                                                                      case 'UPDATE_SECTION_SETTING':
                                                                                                                setConfig((prev) => ({
                                                                                                                            ...prev,
                                                                                                                                        sections: prev.sections.map((section) =>
                                                                                                                                                      section.id === payload.sectionId
                                                                                                                                                                      ? {
                                                                                                                                                                                          ...section,
                                                                                                                                                                                                              settings: {
                                                                                                                                                                                                                                    ...section.settings,
                                                                                                                                                                                                                                                          [payload.settingId]: payload.value,
                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                : section
                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                      }));
                                                                                                                                                                                                                                                                                                                                                break;

                                                                                                                                                                                                                                                                                                                                                        case 'REORDER_SECTIONS':
                                                                                                                                                                                                                                                                                                                                                                  setConfig((prev) => ({
                                                                                                                                                                                                                                                                                                                                                                              ...prev,
                                                                                                                                                                                                                                                                                                                                                                                          layout_order: payload.layoutOrder,
                                                                                                                                                                                                                                                                                                                                                                                                    }));
                                                                                                                                                                                                                                                                                                                                                                                                              break;

                                                                                                                                                                                                                                                                                                                                                                                                                      case 'ADD_SECTION':
                                                                                                                                                                                                                                                                                                                                                                                                                                setConfig((prev) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                            ...prev,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        sections: [...prev.sections, payload.section],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    layout_order: [...prev.layout_order, payload.section.id],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 'REMOVE_SECTION':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setConfig((prev) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ...prev,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  sections: prev.sections.filter((s) => s.id !== payload.sectionId),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              layout_order: prev.layout_order.filter((id) => id !== payload.sectionId),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  window.addEventListener('message', handleMessage);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return () => window.removeEventListener('message', handleMessage);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return <StorefrontRenderer config={config} />;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          